### ISSUE TITLE
Need to clean up the web pages that reference guacamole (in browser vnc) since guacd/tomcat are gone

### ISSUE THREAD

**Issue by subu1962** [digimer/striker#15] opened 2015-03-05 15:38 UTC
The web UI has to be cleaned up to remove attempts at trying to give the user a way to use in browser vnc to a server that has just been configured.

Currently, the "Oh No!" icon appears. guacd/tomcat6 were removed because guac wouldn't support "spice".

**Comment by digimer** [comment] 2015-03-05 15:41
I'm marking this as a bug because, as of now, that's what it is. However, we plan to experiment with other options like noVNC to see if we can find a VNC option that supports spice properly. So we will hold off fixing this until those tests are done, because if we can find one that works, the code behind those icons will be adapted to the new solution. If we can't find an alternative before the next release, these icons will be disabled.

**Comment by digimer** [comment] 2016-01-05 15:44
Closing this as it's not a bug anymore, will create a new issue as an enhancement to restore in-browser access using the SPICE version of noVNC (which has been ruled out as useful at this stage).

**Comment by digimer** [comment] 2016-01-05 15:45
New issue: https://github.com/digimer/striker/issues/20

**Closed by digimer** 2016-01-05 15:44 UTC
Labels: bug
